/*
******************************************************************************
File:     main.cpp
Info:     Generated by Atollic TrueSTUDIO(R) 7.0.1   2016-12-27

The MIT License (MIT)
Copyright (c) 2009-2016 Atollic AB

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
******************************************************************************
*/

/* Includes */

#include <stddef.h>
#include <stdio.h>
#include "stm32f10x.h"
#include "STM32vldiscovery.h"
#include "userSettings.h"
#include "Sensors/HIH6030.h"
#include "Display/Display.h"
#include "math.h"

/* Private macro */
/* Private variables */

/* Private function prototypes */
/* Private functions */

/**
**===========================================================================
**
**  Abstract: main program
**
**===========================================================================
*/
template <typename T>
T abs(T var)
{
	return ((var > 0)? var : (-1 * var));
}

Display ds;
char buf[20];
extern volatile uint16_t ADCVal[4];
static float V1;
static float V2;
static float V3;
static int V3_d;
static int V3_m;
static int V2_d;
static int V2_m;
static int V1_d;
static int V1_m;
void pomiar()
{
	static HIH6030 humSens;
	static int i = 0;
	switch(i)
	{
	case 0: //NO2
	{
		humSens.measureRequest();
		V1 = (float)ADCVal[0]*0.0008056640625;
		V1 = (3.3-V1)/V1;
		V1_d = V1*100;
		break;
	}
	case 1://NO3
	{
		V2 = (float)ADCVal[1]*0.0008056640625;
		V2 = (3.3-V2)/V2;
		V2_d = V2*100;
		ds.clearWindow(5,5,70,20);
		sprintf(buf,"[%i.%i *C]",(humSens.getTemperature()/100),abs(humSens.getTemperature()%100));
		ds.display_string(5,5,buf,FONT_1206,GREEN);
		break;
	}
	case 2://CO
	{
		V3 = (float)ADCVal[2]*0.0008056640625;
		V3 = (3.3-V3)/V3;

		V3_d = V3*100;
		ds.clearWindow(5,20,70,34);
		sprintf(buf,"[%i.%i %c]",(humSens.getHumidity()/100),(humSens.getHumidity()%100),'%');
		ds.display_string(5,20,buf,FONT_1206,GREEN);
		break;
	}
	case 3:
	{
		ds.clearWindow(5,35,96,48);
		sprintf(buf,"%i %i %i",V1_d,V2_d,V3_d);
		ds.display_string(5,35,buf,FONT_1206,GREEN);
		break;
	}
	case 4:
	{
		float temp = (float)ADCVal[3]*0.8056640625;
		ds.clearWindow(5,48,96,63);
		sprintf(buf,"%i.%i *C",(int)temp/100,(int)temp%100);
		ds.display_string(5,48,buf,FONT_1206,GREEN);
		break;
	}
	default:
	{
		humSens.getMeasurements();
		i=0;
		break;
	}
	}
	++i;
}

extern void (*wsk2)();


int main(void)
{
	wsk2 = pomiar;
	init();
	printf("Witaj !\n\r");
	ds.setBackground(BLACK);
	while (1)
	{

	}
}

/*
 * Minimal __assert_func used by the assert() macro
 * */
extern "C" void __assert_func(const char *file, int line, const char *func, const char *failedexpr)
{
  while(1)
  {}
}

/*
 * Minimal __assert() uses __assert__func()
 * */
extern "C" void __assert(const char *file, int line, const char *failedexpr)
{
   __assert_func (file, line, NULL, failedexpr);
}


